name: Laravel on EC2

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up SSH to EC2 instance using the private key from secrets
    - name: Set up SSH to EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Run Laravel setup and tests on EC2 instance
    - name: Run Laravel setup and tests on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/laraveldemo

          # Copy .env if it doesn't exist
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

          # Install Composer dependencies
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

          # Generate the application key if not set
          if grep -q "APP_KEY=" .env; then
            echo "App key already set"
          else
            php artisan key:generate
          fi

          # Run tests without database
          vendor/bin/phpunit --no-coverage
        EOF
